# Build settings

markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']
exclude: ["the_design.psd", "node_modules", "gulpfile.js", "package.json"]

sass:
  sass_dir: assets/css
  style: :nested
